### ISSUE TITLE
get_chain() method in markov_chain.py returns an empty list for some .mid files

### ISSUE THREAD

**Issue by ashishrana160796** [omgimanerd/markov-music#5]
Error Message while running the following attached files in `.mid` extension :

[Adana.txt](https://github.com/omgimanerd/markov-music/files/1958980/Adana.txt)
[JaunaPuri.txt](https://github.com/omgimanerd/markov-music/files/1958981/JaunaPuri.txt)
`Note`
Change extension to `.mid` to run these files.

```
Traceback (most recent call last):
  File "src/generator.py", line 45, in <module>
    Generator.load(chain).generate(sys.argv[2])
  File "src/generator.py", line 33, in generate
    new_note = self.markov_chain.get_next(last_note)
  File "/home/user_name/Desktop/markov-music-master/src/markov_chain.py", line 37, in get_next
    random_chain = self.chain[random.choice(list(self.chain.keys()))]
  File "/usr/lib/python3.5/random.py", line 255, in choice
    raise IndexError('Cannot choose from an empty sequence')
IndexError: Cannot choose from an empty sequence

```
get_chain() method returns an empty list for these files. Which leads to conclusion that current chain creation function doesn't handle files like these where there is no direct link between `from` and `to` notes.

**Comment by omgimanerd** [comment]
This repository is meant to be an archive for the linked blog post, so I most likely will not be updating this or fixing this anytime soon.

**Comment by ashishrana160796** [comment]
Sounds reasonable to me as consistency is important with post.
